
name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t python-project

      - name: Log in to Docker Hub
        run: docker login -u goheersajjad97 -p Transdata!@#

      - name: Push Docker image to Docker Hub
        run: docker push python-project

      - name: SSH into DigitalOcean droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 188.166.165.242
          username: root
          key: Welcome@023@W2a
          script: |
            docker pull python-project
            docker-compose -f docker-compose.yml up -d
