name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main # Change to the branch you want to deploy

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        docker-compose --version
      shell: bash

    - name: Copy Docker Compose files to the Droplet
      run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r docker-compose.yml root@188.166.165.242:/root/python-project/python-project
      env:
        SSH_PASSWORD: Welcome@023@W2a

    - name: SSH into the Droplet, pull the latest code, and deploy the application
      run: |
        sshpass -p Welcome@023@W2a ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@188.166.165.242 "cd /root/python-project/python-project && git pull && docker-compose up -d"
      env:
        SSH_PASSWORD: Welcome@023@W2a
