name: Deploy to DigitalOcean Droplet
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to DigitalOcean 
          uses: appleboy/ssh-action@v1.0.0
          with:
          host: 188.166.165.242
          username: root
          key: Welcome@023@W2a
          script: |
            rm -rf test
            mkdir test
            git clone https://github.com/goheersajjadtradata/python-project.git
            cd python-project
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d
             echo 'Deployment to digital ocean finished'
