
name: Deploy to DigitalOcean Droplet
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: 188.166.165.242
          username: root
          key: Welcome@023@W2a
          script: |       
            cd /python-project
            git clone git@github.com:goheersajjadtradata/python-project.git
            echo 'Deployment to digital ocean finished'
